version: "3.3"

networks:
    traefik-net:
      external: true

services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#     - /opt/portainer/data:/data
    deploy:
      labels:
        - "com.df.notify=true"
        - "com.df.scrapePort=9000"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:mydomain.lan;PathPrefixStrip:/portainer"
        - "traefik.docker.network=traefik-net"
    depends_on:
      - traefik-ssl

  watchtower:
    image: v2tec/watchtower
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
