# not working
#version: "3.3"

networks:
    traefik-net:
      external: true
    consul-net:
      external: true

services:

  traefik:
    image: traefik
    command: --consul --consul.endpoint=consul:8500
    networks:
      - traefik-net
      - consul-net
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONSUL_HTTP_TOKEN=test
