version: '3.3'

networks:
    proxy:
      external: true

volumes:
    data:

configs:
  traefik.toml:
    file: ./traefik-ssl.toml
  mydomain.lan.crt:
    file: ./mydomain.lan.crt
  mydomain.lan.key:
    file: ./mydomain.lan.key

services:

    traefik-ssl:
      image: traefik
      command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --docker.domain=mydomain.lan --logLevel=DEBUG
      networks:
        - proxy
      ports:
        - "443:443"
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
#       - /dockerdata/traefik/log:/log
      deploy:
        mode: global
        labels:
          - "com.df.notify=true"
          - "com.df.scrapePort=8080"
          - "traefik.port=8080"
      configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
        mode: 0444
      - source: mydomain.lan.crt
        target: /certs/mydomain.lan.crt
        mode: 0444
      - source: mydomain.lan.key
        target: /certs/mydomain.lan.key
        mode: 0444
